# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: api-dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: f85c3ad7-23ac-4a35-9d25-9022c5ae3fc9
    keyvaultName: team5kv
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: SQL-PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-USER
          objectType: secret
          objectVersion: ""
    tenantId: 251861b5-e3c8-4a8e-801f-5e9f7606b39c