# This is a SecretProviderClass example using user-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault
  namespace: api-dev
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: 0ac311ba-36d5-433c-9337-00874e05b0ae
    keyvaultName: team5kv
    cloudName: ""
    objects:  |
      array:
        - |
          objectName: SQL-PASSWORD
          objectAlias: SQL_PASSWORD
          objectType: secret
          objectVersion: ""
        - |
          objectName: SQL-USER
          objectAlias: SQL_USER
          objectType: secret
          objectVersion: ""
    tenantId: 251861b5-e3c8-4a8e-801f-5e9f7606b39c